# Define reactive values
reactive_values <- reactiveValues(
  file_data = NULL,
  user_subjects = NULL,
  user_dates = NULL,
  user_variables = NULL,
  user_data = NULL
)

# Define bibliographic standard bounds
bibliographic_standard_bounds <- data.frame(
  Variable = c(
    "Body Fat (%)",
    "Blood Urea Nitrogen (mg/dL)",
    "Magnesium (mmo/L)",
    "Bilirubin (mg/dL)",
    "Lactate Dehydrogenase (U/L)",
    "Creatine Kinase (U/L)",
    "Urid Acid (mg/dL)",
    "C Reactive Protein (mg/L)",
    "Sodium (mmol/L)",
    "Potassium (mmol/L)",
    "Calcium (mmol/L)",
    "Myoglobin (ng/ml)",
    "Cholesterol (mg/dL)",
    "HDL (mg/dL)",
    "LDL (mg/dL)",
    "Triglyceride (mg/dL)",
    "Glucose (mg/dL)",
    "WBC (per \u00B5L)",
    "Neutrophils (%)",
    "Lymphocytes (%)",
    "Neutrophils-to-Lymphocyte Ratio",
    "Monocytes (%)",
    "Eosinophile (%)",
    "Basophil (%)",
    "Platelets (per nL)",
    "RBC(per pL)",
    "Hemoglobin (g/dL)",
    "MCV (fL)",
    "Hematocrit (%)",
    "MCH (pg)",
    "MCHC (g/dL)",
    "Transferrin (g/L)",
    "Ferritin (\u00B5g/L)",
    "Iron (\u00B5moL/L)",
    "Transferrin Saturation (%)",
    "Testosterone (ng/dL)",
    "Cortisol (\u00B5g/dL)",
    "IL-6 (ng/mL)",
    "Vitamin E (mg/L)",
    "Vitamin B6 (\u00B5g/L)",
    "Vitamin B12 (pg/mL)",
    "Vitamin C (mg/L)",
    "1,25-dihydroxyvitamine D (\u00B5g/L)"
  ),
  Minimum = c(
    4,
    5,
    0.7,
    0.1,
    105,
    55,
    3.5,
    0,
    136,
    3.6,
    2.2,
    25,
    125,
    40,
    0,
    0,
    70,
    4500,
    40,
    22,
    1,
    4,
    0,
    0,
    150,
    4.7,
    13,
    80,
    40,
    27,
    32,
    1.8,
    30,
    10,
    20,
    300,
    10,
    0,
    5.5,
    5,
    160,
    5,
    18
  ),
  Maximum = c(
    16,
    20,
    1.1,
    1.2,
    230,
    170,
    7.2,
    3,
    145,
    5.2,
    2.7,
    72,
    200,
    70,
    100,
    150,
    100,
    11000,
    60,
    44,
    11,
    11,
    8,
    3,
    400,
    6.1,
    17,
    100,
    54,
    33,
    36,
    3.3,
    300,
    30,
    50,
    1000,
    20,
    5,
    17,
    30,
    950,
    15,
    64
  )
)